# Generated by Django 5.2.4 on 2025-07-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=64)),
                ('staff_id', models.CharField(max_length=24, unique=True)),
                ('title', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], default='lecturer', max_length=64)),
                ('department_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teacher_list',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('student_id', models.CharField(max_length=24, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('class_president', 'Class President'), ('class_officer', 'Class Officer')], default='student', max_length=64)),
                ('department_id', models.CharField(max_length=64)),
                ('enroll_year', models.IntegerField()),
                ('class_id', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to='school.teacher')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='school.teacher')),
            ],
            options={
                'db_table': 'student_list',
            },
        ),
    ]
